provider = "github"
default_branch = "main"

[release_pr]

[release_pr.changelog]
enabled = true
provider = "changelogen"

[release_pr.tagging]
enabled = true
tag_template = "v{version}"

[release_pr.format_overrides]
"Cargo.lock" = "toml"

[release_pr.version_updates]
"Cargo.toml" = ["package.version"]
"Cargo.lock" = ["package[name=tusklet].version"]
